# Generated by Django 5.1.3 on 2024-11-18 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_code",
                    models.TextField(null=True, verbose_name="Исходный код"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 18, 7, 4, 20, 150703),
                        verbose_name="Создано",
                    ),
                ),
            ],
        ),
    ]
