# Generated by Django 5.1.3 on 2024-11-18 01:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 7, 7, 59, 630672),
                verbose_name="Создано",
            ),
        ),
        migrations.CreateModel(
            name="Coder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fio",
                    models.CharField(max_length=200, null=True, verbose_name="ФИО"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="published_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.coder",
                verbose_name="Автор",
            ),
        ),
    ]
