# Generated by Django 5.1.3 on 2024-11-18 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_task_date_coder_task_published_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 7, 9, 39, 401578),
                verbose_name="Создано",
            ),
        ),
    ]
