# Generated by Django 5.1.3 on 2024-11-18 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_task_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 7, 20, 15, 417612),
                verbose_name="Создано",
            ),
        ),
    ]
