# Generated by Django 5.1.3 on 2024-11-18 01:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_task_name_alter_task_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coder",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 7, 30, 31, 59793),
                verbose_name="Создано",
            ),
        ),
    ]
