# Generated by Django 5.1.3 on 2024-11-18 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_task_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 18, 1, 33, 22, 182359, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Создано",
            ),
        ),
    ]
