# Generated by Django 5.1.3 on 2024-11-18 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_task_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
    ]
