# Generated by Django 5.1.3 on 2024-11-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_task_published_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание задания"),
        ),
    ]
