# Generated by Django 5.1.3 on 2024-11-18 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_task_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskComplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(null=True, verbose_name="Код решения")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Решено"
                    ),
                ),
                (
                    "coder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.coder"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.task"
                    ),
                ),
            ],
        ),
    ]
