# Generated by Django 5.1.3 on 2024-11-27 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_taskcomplete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskcomplete",
            old_name="coder",
            new_name="solved_by",
        ),
        migrations.AlterField(
            model_name="taskcomplete",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
