# Generated by Django 5.1.3 on 2024-11-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_taskcomplete_solved_by_alter_taskcomplete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomplete",
            name="solved_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.coder"
            ),
        ),
    ]
