# Generated by Django 5.1.3 on 2024-11-27 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_taskcomplete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomplete",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.task"
            ),
        ),
    ]
