# Generated by Django 5.1.3 on 2024-11-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_taskcomplete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcomplete",
            name="solved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.coder",
            ),
        ),
    ]
